Repository chorhatarahuduketuri/gc, pull requests merged in 2018-07, with the labels that each got.

#51 Lots of small fixes
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
Labels: bug

#54 Improved readability: Reduced redundant code and global variables
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
Labels: Code Quality

#69 Enhancement/colonisation
  app/src/main/java/dadeindustries/game/gc/mechanics/units/UnitActions.java
  app/src/main/java/dadeindustries/game/gc/model/GlobalGameData.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/Sector.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/phenomena/Planet.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/phenomena/System.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
  app/src/main/res/drawable-mdpi/system1.png
  app/src/main/res/drawable-mdpi/system2.png
Labels: enhancement

#70 Update README
  README.md
  docs/screenshot.png
Labels: documentation

#72 Enhancement/hierarchical context menu
  app/src/main/java/dadeindustries/game/gc/mechanics/Event.java
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/model/Coordinates.java
  app/src/main/java/dadeindustries/game/gc/model/GlobalGameData.java
  app/src/main/java/dadeindustries/game/gc/model/players/Player.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/Sector.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/phenomena/System.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
  app/src/main/java/dadeindustries/game/gc/view/Start.java
Labels: enhancement

#73 Enhancement/basic ai
  app/src/main/java/dadeindustries/game/gc/ai/Mind.java
  app/src/main/java/dadeindustries/game/gc/ai/concepts/Location.java
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/model/GlobalGameData.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/phenomena/System.java
Labels: enhancement

#74 Minor enhancements to the hierarchical menu
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/model/GlobalGameData.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/Sector.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
Labels: enhancement

#77 Feature/show colonisation event
  app/src/main/java/dadeindustries/game/gc/mechanics/Event.java
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/mechanics/units/UnitActions.java
  app/src/main/java/dadeindustries/game/gc/model/factionartifacts/ColonyShip.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
  app/src/main/java/dadeindustries/game/gc/view/Start.java
  app/src/main/res/drawable-mdpi/colonise.jpg
  app/src/main/res/layout/colonyevent.xml
Labels: enhancement

#76 Fix issue of multiple reports per sector
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/Sector.java
Labels: bug

#79 Implemented pinch-to-zoom functionality. Very slick.
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
Labels: enhancement

#80 Game over screen can no longer be dismissed
  app/src/main/java/dadeindustries/game/gc/view/Start.java
Labels: bug

#83 New summary button + misc UI improvements
  app/src/main/java/dadeindustries/game/gc/mechanics/Event.java
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
  app/src/main/java/dadeindustries/game/gc/view/Start.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#85 Mechanics/decouple player from faction
  app/src/main/java/dadeindustries/game/gc/ai/Mind.java
  app/src/main/java/dadeindustries/game/gc/mechanics/turn/TurnProcessor.java
  app/src/main/java/dadeindustries/game/gc/mechanics/units/UnitActions.java
  app/src/main/java/dadeindustries/game/gc/model/GlobalGameData.java
  app/src/main/java/dadeindustries/game/gc/model/factionartifacts/ColonyShip.java
  app/src/main/java/dadeindustries/game/gc/model/factionartifacts/CombatShip.java
  app/src/main/java/dadeindustries/game/gc/model/factionartifacts/Spacecraft.java
  app/src/main/java/dadeindustries/game/gc/model/factionartifacts/Spaceship.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/Sector.java
  app/src/main/java/dadeindustries/game/gc/model/stellarphenomenon/phenomena/System.java
  app/src/main/java/dadeindustries/game/gc/view/GalaxyView.java
Labels: enhancement
